# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c7bf0aabe220f5f3ee5adf80f2c3c95f92127ffd85ace0f85ced61bffdf6adb731b692bf0ff3964262f6eb4b13f5d972777def0569e3059b4278115b1bedc3

test:
  secret_key_base: 36fffab930b63d98c3fefbde873947900270dbf89191ee5796a500ee5fd58b22ce4728f07ef3010b7157e2c34036102c42904f3d63451fdcd04bbaee8a74e52d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
